/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary:              '#006a62',
        'primary-container':  '#35a79c',
        'on-primary':         '#ffffff',
        'on-primary-container':'#003631',
        secondary:            '#465f88',
        'secondary-container':'#b6d0ff',
        'on-secondary':       '#ffffff',
        tertiary:             '#735c00',
        'tertiary-fixed':     '#ffe088',
        'on-tertiary-fixed':  '#241a00',
        'tertiary-container': '#cba72f',
        surface:              '#f9f9ff',
        'surface-container':  '#e7eeff',
        'surface-container-low':'#f0f3ff',
        'surface-container-high':'#dfe8ff',
        'surface-container-highest':'#d6e3ff',
        'on-surface':         '#001b3d',
        'on-surface-variant':  '#3d4947',
        'on-background':       '#001b3d',
        'outline':             '#6d7a77',
        'outline-variant':     '#bcc9c6',
        'inverse-surface':     '#143057',
        'inverse-on-surface':  '#ecf0ff',
        'inverse-primary':     '#6dd8cc',
        'primary-fixed':       '#8af5e8',
        'primary-fixed-dim':   '#6dd8cc',
        'surface-variant':     '#d6e3ff',
        'error':               '#ba1a1a',
        'error-container':     '#ffdad6',
        gold:                  '#F4A261',
        'gold-dark':           '#D4854A',
        navy:                  '#1B3A4B',
        'navy-light':          '#2E5A6E',
        teal:                  '#2A9D8F',
        'teal-light':          '#E8F7F5',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['"Manrope"', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
